spring:
  application:
    name: "gateway-server"
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
server:
  port: 8888

#spring:
#  application:
#    name: "gateway-server"
#  cloud:
#    config:
#      enabled: false
#    gateway:
#      routes:
#        - id: auth-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/v1/auth/**
#        - id: blog-service
#          uri: http://localhost:8090
#          predicates:
#            - Path=/api/v1/blog/**
#      discovery:
#        locator:
#          enabled: false
#          lowerCaseServiceId: true
#
#app:
#  api-prefix: /api/v1
#  url:
#    auth: "http://localhost:8080/auth"
#
#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: "http://localhost:8070/eureka/"
#
#info:
#  app:
#    name: "gateway-server"
#    description: "JobHunter Gateway Server Application"
#    version: "1.0.0"
