server:
    port: 8090

spring:
    application:
        name: blog-service
    cloud:
        compatibility-verifier:
            enabled: false
        config:
            enabled: false

    datasource:
        url: jdbc:mysql://localhost:3307/blogdb
        username: root
        password: root
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
redis:
    host: localhost
    port: 6379

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: "http://localhost:8070/eureka/"