version: "3.8"
services:
  authdb:
    image: mysql
    container_name: authdb-local
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_ROOT_PASSWORD: root

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-local
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka-edu-local
    hostname: localhost
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

